# Generated by Django 5.0.3 on 2024-08-27 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queue_requests', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queuereuqest',
            old_name='user',
            new_name='user_related',
        ),
    ]
