# Generated by Django 5.0.3 on 2024-08-27 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queue_requests', '0003_rename_user_queuereuqest_user_related'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queuereuqest',
            name='user_related',
        ),
    ]
