# Generated by Django 3.2.15 on 2025-04-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(default='santiagomunoz319@gmail.com', max_length=254, unique=True),
        ),
    ]
