# Generated by Django 3.2.15 on 2025-04-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(default='user', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
