# Generated by Django 3.2.15 on 2025-07-15 00:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_board', '0004_message_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discussion_board_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='discussionboardrequest',
            unique_together={('discussion_board', 'user')},
        ),
    ]
