# Generated by Django 3.2.15 on 2025-08-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_board_requests', '0002_alter_discussionboardrequest_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionboardrequest',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
