# Generated by Django 3.2.15 on 2025-09-04 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_board_requests', '0003_discussionboardrequest_message'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='discussionboardrequest',
            unique_together=set(),
        ),
    ]
