# Generated by Django 5.0.3 on 2024-04-22 23:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Queues',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('admin', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_queues', to=settings.AUTH_USER_MODEL)),
                ('components', models.ManyToManyField(blank=True, related_name='queues_components', to='components.components')),
                ('users', models.ManyToManyField(blank=True, related_name='queues_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
