# Generated by Django 5.0.3 on 2024-05-29 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0001_initial'),
        ('queues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='queues',
            name='admin',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_queues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='queues',
            name='components',
            field=models.ManyToManyField(blank=True, related_name='queues_components', to='components.components'),
        ),
        migrations.AddField(
            model_name='queues',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='queues_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
