# Generated by Django 5.0.3 on 2024-08-27 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('ALISTANDO', 'Alistando'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado')], default='RECIBIDO', max_length=20)),
            ],
        ),
    ]
