# Generated by Django 5.0.3 on 2024-06-27 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='components',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='users',
        ),
    ]
