# Generated by Django 5.0.3 on 2024-06-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_remove_requests_admin_remove_requests_components_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='status',
            field=models.CharField(choices=[('RECIBIDO', 'Recibido'), ('ALISTANDO', 'Alistando'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado')], default='RECIBIDO', max_length=20),
        ),
    ]
