# Generated by Django 5.0.3 on 2024-06-29 06:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_requests_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='id',
            field=models.AutoField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
