# Generated by Django 5.0.3 on 2024-03-19 00:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('referencia', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.providers')),
            ],
        ),
    ]
