# Generated by Django 5.0.3 on 2024-04-22 23:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=250, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('image_url', models.CharField(blank=True, max_length=250)),
                ('datasheet_url', models.CharField(blank=True, max_length=250)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='providers.providers')),
            ],
        ),
    ]
