# Generated by Django 5.0.3 on 2024-04-16 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='components',
            name='datasheet_url',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='components',
            name='image_url',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='components',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='providers.providers'),
        ),
    ]
