# Generated by Django 3.2.15 on 2025-04-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='components',
            name='price_breaks',
            field=models.TextField(blank=True),
        ),
    ]
