# Generated by Django 5.0.3 on 2024-07-09 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='components',
            name='datasheet_url',
        ),
        migrations.AddField(
            model_name='components',
            name='search_index_provider',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
