# Generated by Django 5.0.3 on 2024-07-09 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_remove_components_datasheet_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='components',
            name='datasheet_url',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
