# Generated by Django 3.2.15 on 2025-04-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_components_price_breaks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='components',
            name='price_breaks',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
