# Generated by Django 3.2.15 on 2025-04-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_alter_components_price_breaks'),
    ]

    operations = [
        migrations.AddField(
            model_name='components',
            name='stock_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
