# Generated by Django 3.2.15 on 2025-03-26 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionBoard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('autoacept', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_discussion_boards', to=settings.AUTH_USER_MODEL)),
                ('components', models.ManyToManyField(blank=True, related_name='discussion_boards_components', to='components.Components')),
                ('users', models.ManyToManyField(blank=True, related_name='discussion_boards_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
