# Generated by Django 3.2.15 on 2025-06-25 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('components', '0004_components_stock_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionBoard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referencia', models.CharField(blank=True, max_length=1000)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('nombre', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('autoacept', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('created', 'Creado'), ('filling_participants', 'Llenando Participantes'), ('closed', 'Cerrado')], default='created', max_length=20)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_discussion_boards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
                ('discussion_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='discussion_board.discussionboard')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='discussion_board.message')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscussionBoardComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.components')),
                ('discussion_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussion_board.discussionboard')),
            ],
            options={
                'unique_together': {('discussion_board', 'component')},
            },
        ),
        migrations.AddField(
            model_name='discussionboard',
            name='components',
            field=models.ManyToManyField(blank=True, related_name='discussion_boards_components', through='discussion_board.DiscussionBoardComponent', to='components.Components'),
        ),
        migrations.AddField(
            model_name='discussionboard',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='discussion_boards_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
