# Generated by Django 3.2.15 on 2025-07-14 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_board_requests', '0001_initial'),
        ('components', '0004_components_stock_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discussion_board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionboardcomponent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discussionboardcomponent',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='discussion_board_requests.discussionboardrequest'),
        ),
        migrations.AddField(
            model_name='discussionboardcomponent',
            name='type',
            field=models.CharField(choices=[('initial', 'Inicial'), ('request', 'Request')], default='initial', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='discussionboardcomponent',
            unique_together={('discussion_board', 'component', 'created_by', 'type')},
        ),
    ]
