# Generated by Django 3.2.15 on 2025-07-14 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_board', '0002_auto_20250714_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionboardcomponent',
            name='discussion_board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discussion_board.discussionboard'),
        ),
    ]
