# Generated by Django 3.2.15 on 2025-04-03 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_board', '0003_discussionboard_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionboard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-04-02 21:59:42.116252'),
            preserve_default=False,
        ),
    ]
