# Generated by Django 3.2.15 on 2025-07-15 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_board_requests', '0001_initial'),
        ('discussion_board', '0003_alter_discussionboardcomponent_discussion_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='discussion_board_requests.discussionboardrequest'),
        ),
    ]
