# Generated by Django 3.2.15 on 2025-09-05 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_board', '0004_message_request'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='discussionboardcomponent',
            unique_together=set(),
        ),
    ]
