# Generated by Django 3.2.15 on 2025-04-17 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discussion_board', '0005_auto_20250402_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionboard',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_discussion_boards', to=settings.AUTH_USER_MODEL),
        ),
    ]
