# Generated by Django 3.2.15 on 2025-09-05 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_board', '0005_alter_discussionboardcomponent_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='components',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
